
spring:
  datasource:
    url: ${{secrets.DB_URL}}
    username: ${{secrets.DB_USERNAME}}
    password: ${{secrets.DB_PASSWORD}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${{secrets.MAIL_USERNAME}}
    password: ${{secrets.MAIL_PASSWORD}}
    properties:
      mail:
        smtp:
          trust: "*"
          starttls:
            enable: true
            required: true
        auth: true
        starttls:
          enabled: true
        connection-timeout: 5000
        timeout: 3000
        write-timeout: 5000
application:
  security:
    jwt:
      secret: ${{secrets.JWT_SECRET}}
      expired:
        access:  1000000
        refresh:  2592000000
server:
  port: 8080
